name: test project
on: push
jobs:
  pre-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm install
  lint:
    runs-on: ubuntu-latest
    needs: pre-job
    steps:
      - name: Lint
        run: npx eslint --ext .jsx --fix src
  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Test
        run: npx vitest run
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Build
        run: npx vite build
